### ISSUE TITLE
Add pipeline validation

### ISSUE THREAD

**Issue by drwl** [Gusto/buildkite-builder#6]
Buildkite offers pipeline.yml schema validation tools: https://github.com/buildkite/pipeline-schema

The JSON https://raw.githubusercontent.com/buildkite/pipeline-schema/master/schema.json

It would be nice to have a way to test if `pipeline.rb`s are valid.

**Comment by technicalpickles** [comment]
I did some exploration on this. There are a few gems out there for JSON validation, which can generally stand in for YAML validation too.

There's a few gems for this.
- [voxpupuli/json-schema: Ruby JSON Schema Validator](https://github.com/voxpupuli/json-schema)
- [davishmcclurg/json_schemer: JSON Schema validator. Supports drafts 4, 6, and 7.](https://github.com/davishmcclurg/json_schemer)

The [JSON Schema website only mentions json_schemer](https://json-schema.org/implementations.html) for Ruby implementations. I think because it is the only that supports all the draft.

I tested both... I ran into a problem where json-schema doesn't fails with an error because the pipeline schema uses draft 6 which json-schema doesn't support.

I had slightly better success with jsonschemer in getting it to validate. Right now it thinks the generated file isn't valid, but I haven't been able to get out specific errors yet. I'm not sure if it's lack of familiarity with JSON schemas, the gem, or this gem yet though 😅  I'll push up a draft PR with more info.


That all said, I'm wondering how much benefit there is to doing local validation, when uploading to buildkite will be the real way to validate the thing works. We'll find out pretty quick if the schema changes in a way that affects builds.
